# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f120fb276ed6ec9ab8f408459ad94bc6ebf2eae5766cfd44381503d0c16b918ec99e3092ffe168a7f9fa3a02859803bcb0d313ebcb0267be6fd89e2fb81ab64

test:
  secret_key_base: 8be07bd60843d6899f8a50ec475f87bb1f1549cc09eac88eb7abf8eeca0db3841f7c7de1e01db45925d940d6e48d37500b043a20b9e98d59cff585d0ea3b242e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
